-- Accounts are intentionally PENDING_EMAIL until an email is added.
-- Tristan and Steven are the initial System Owners.

INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-706279', '706279', '2d Lt', 'Janelle C Allison', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-249023', '249023', '1st Lt', 'Ernest E Burchell', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-744144', '744144', '2d Lt', 'Rebecca J Chretien', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-744143', '744143', '2d Lt', 'Everett J Chretien', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-766637', '766637', 'SM', 'Guy R Cooper', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-764706', '764706', 'SM', 'Andrew Diaz', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-735120', '735120', '2d Lt', 'Margaret A Durgin', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-766638', '766638', 'SM', 'Amanda L Harvey', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-411177', '411177', '1st Lt', 'Zachary D Johnson Jr', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-450227', '450227', 'Maj', 'Clarence M Juneau', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-729204', '729204', '2d Lt', 'Tristan G Maratos', NULL, NULL, 'OWNER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-326320', '326320', 'Maj', 'Steven C Mellard', NULL, NULL, 'OWNER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-736465', '736465', 'SM', 'Desiree Morse', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-757794', '757794', '2d Lt', 'Tonya M Osborne', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-702226', '702226', '1st Lt', 'Mel W Osborne', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-621484', '621484', 'SM', 'Sandra L Puska', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-740617', '740617', '2d Lt', 'Tyler M Thomas', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-270831', '270831', 'Maj', 'Timothy S Waddell', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-657945', '657945', '2d Lt', 'Anthony A Warthan', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-662670', '662670', '2d Lt', 'Colleen J Warthan', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO users (id, capid, rank, full_name, email, email_norm, role, status, created_at, updated_at) VALUES ('cap-738555', '738555', 'SM', 'Jesse W Wilkie', NULL, NULL, 'MEMBER', 'PENDING_EMAIL', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
