import { StatCard } from "@squadron/ui";

const stats = [
  { label: "Overdue Items", value: 18, tone: "danger" as const },
  { label: "Due This Week", value: 7, tone: "warning" as const },
  { label: "Awaiting Approval", value: 5, tone: "warning" as const },
  { label: "Open Tasks", value: 12, tone: "info" as const },
  { label: "Readiness Score", value: "93%", tone: "success" as const }
];

export function CommandDashboard() {
  return (
    <main style={{ padding: 32 }}>
      <header style={{ marginBottom: 24 }}>
        <p style={{ color: "var(--muted)", margin: 0 }}>TN-170 Oak Ridge Composite Squadron</p>
        <h1 style={{ marginTop: 8 }}>Command Dashboard</h1>
      </header>

      <section
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
          gap: 16
        }}
      >
        {stats.map((stat) => (
          <StatCard key={stat.label} {...stat} />
        ))}
      </section>

      <section
        style={{
          display: "grid",
          gridTemplateColumns: "2fr 1fr",
          gap: 20,
          marginTop: 24
        }}
      >
        <div style={panelStyle}>
          <h2>Priority Items</h2>
          <p style={{ color: "var(--muted)" }}>
            Tasks, compliance requirements, and commander actions will appear here.
          </p>
        </div>

        <div style={panelStyle}>
          <h2>Upcoming Deadlines</h2>
          <p style={{ color: "var(--muted)" }}>
            Recurring suspense items generated by the worker service will appear here.
          </p>
        </div>
      </section>
    </main>
  );
}

const panelStyle = {
  background: "var(--surface)",
  border: "1px solid var(--border)",
  borderRadius: 14,
  padding: 20
};
